import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';
import eslintConfigPrettier from 'eslint-config-prettier';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  // Global ignores (ESLint 9 ignores node_modules by default, but not these).
  {
    ignores: [
      '.next/**',
      'Output/**',
      'Docs/**',
      'data/**',
      '.claude/**', // Claude Code skills/config — not app source
      '.agents/**', // vendored agent/skill content — not app source
      'spec-extracted/**', // generated by scripts/extract-spec.mjs
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  eslintConfigPrettier, // must come last to win over stylistic rules
];

export default eslintConfig;
